# Use the offcial Node.js image as a base
FROM node:20.18.0

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose backend port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
